export const data = [
    {
      id: "11",
      title:"Exercise involves engaging in physical activity",
      url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW2Ut5UlDMlMbAGGm4zyMgGmfgjRuD4tYEjg&usqp=CAU",
      content:"Whether people engage in light exercise, such as going for a walk, or high intensity activities, for example, uphill cycling or weight training, regular exercise provides a huge range of benefits for the body and mind.",
      category:"Fitness",      
      date:"On September 20, 2015.",
      width: 500,
      height: 307,
    },
    {
      id: "12",
      title:"The Fitness Factory, a one-stop-shop for all fitness needs launched",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiiqavn_C6YY8U_S-oRFDEPwHF2YLKs_cXow&usqp=CAU",
      content:"A Surat-based fitness enthusiast turned entrepreneur has launched The Fitness Factory, a one-stop-shop for fitness freaks and the first of its kind in India.",
      category:"Fitness",
      date:"On March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "13",
      title:"A Fresh Perspective on Physical Activity",
      url:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKscGuRV1LWOi6iTVTPcKH2WLg8_n13y4mgg&usqp=CAU",
      content:"In the big picture of physical activity, everything counts!  Running a 5k, sweating during spin or Krank class, and lifting weights are not the only examples of physical activity.",
      category:"Physical Activity Pyramid",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "a14",
      title:"Close up hands. Woman do yoga outdoor",
      url:" https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJM6k906ZylArm8uXUxNHsmHadwXq-E_pkQw&usqp=CAU",
      content:"Close up hands. Woman do yoga outdoor. Woman exercising vital and meditation for fitness lifestyle in the beach sunset background. Healthy Concept",
      category:"Yoga",
      date:" On September 20, 2015.",
      width: 700,
      height: 524,
    },
    {
      id: "15",
      title:"Benefits of Running",
      url: "https://www.mensjournal.com/wp-content/uploads/2015/08/RunningBenefitsMain1.jpg?quality=86&strip=all",
      content:"Running is hugely popular, and there are all kinds of ways to do it, from jogging around the neighborhood to trail running or signing up for a race. After a pause due to the pandemic. ",
      category:"healthy Food",
      date:"On September 20, 2015.",
      width: 2696,
      height: 3546,
    },
  
    {
      id: "iwfwfw2ew",
      title:"Healthy lifestyle fitness sports woman running",
      url: "https://thumbs.dreamstime.com/z/healthy-lifestyle-fitness-sports-woman-running-sunrise-road-39709089.jpg",
      content:"Healthy lifestyle fitness sports woman running at sunrise road",
      category:"Fitness",
      date:"On March 2, 2019.",
      width: 640,
      height: 427,
    },
  ];
  