export const data = [
    {
      id: "11",
      title:"Foods to Eat in the Morning",
      url: "https://post.healthline.com/wp-content/uploads/2021/10/fruit-salad-best-breakfast-foods-1296x728-body.jpg",
      content:"A balanced breakfast typically includes protein, fiber, and produce. If you’re looking to build a healthy morning meal, try easy options like eggs, whole wheat toast with toppings, nuts, and green tea.",
      category:"costumes",
      date:"On March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "12",
      title:"Beer Soup? No. Greens? Yes.",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnX14K7ANHrOoIgHNdIjOu4chJ-DjaOfOwyw&usqp=CAU",
      content:"American breakfasts are heavy on foods that make us heavy.Credit...Alanna Taylor-Tobin and Sarah Menanix for The New York Times.",
      category:"Wine",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "13",
      title:"Healthy People Eat In Breakfast",
      content:"A right breakfast not only keeps you fit but also curbs your mid-meal cravings. Choosing a healthy breakfast option is a complex task, especially, when you desire to taste as well as nutrition at the same time.",
      category:"Food",
      date:"On January 31, 2010",
      url: "https://post.healthline.com/wp-content/uploads/2020/08/salad-for-breakfast-732x549-thumbnail-732x549.jpg",
      width: 640,
      height: 428,
    },
    {
      id: "14",
      title:"Food waste",
      url: "https://foodprint.org/wp-content/uploads/2018/10/food-waste-problem.jpg",
      content:"A pile of food waste, such as eggshells and fruit and vegetable peels, on a white background",
      category:"Food",
      date:"On September 30, 2020",
      width: 450,
      height: 600,
    },
    {
      id: "15",
      title:"Reduce food waste and save some money",
      url: "https://softengine.com/wp-content/uploads/2021/04/zero-waste-300x200.jpeg",
      content:"As per the Food Waste Index Report 2021 by the United Nations Environment Programme (UNEP), Indians throw away 50 kg of food per person every year.",
      category:"Wasting Food",
      date:"On 25 December 2012.",
      width: 1193,
      height: 1006,
    },
  ];