export const data = [
    {
      id: "cwaww334r4222dadm5",
      title:"FITNESS",
      url: "https://thumbs.dreamstime.com/z/fitness-word-cloud-sport-health-concept-58066979.jpg",
      content:"FITNESS word cloud, sport, health concept",
      category:"Fitness",
      date:"On March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "tewf343fgugmkfhd5s",
      title:"Laboratory",
      url: "https://thumbs.dreamstime.com/z/laboratory-18359431.jpg",
      content:"Scientists working at the laboratory",
      category:"Technology",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "tk9okifhgjhtb",
      title:"Pouring wine into glass and food",
      url: "https://thumbs.dreamstime.com/b/pouring-wine-glass-food-28336625.jpg",
      content:"Pouring wine into glass and food background",
      category:"Wine",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "t23ddeht7900ugukfhd5s",
      title:"Asian fitness woman runner stretching legs before run outdoor workout in the park.",
      url: "https://thumbs.dreamstime.com/z/asian-fitness-woman-runner-stretching-legs-run-outdoor-workout-park-healthy-concept-106427114.jpg",
      content:"Asian fitness woman runner stretching legs before run outdoor workout in the park. Healthy Concept.",
      category:"warmUp",
      date:"On December 21,2021",
      width: 500,
      height: 500,
    },
  ];