export const data = [
    {
      id:"1",
      title:"Online Reviews Evaluation Concept with computer halogram scanning on data of business and all new technology",
      url:"https://thumbs.dreamstime.com/b/online-reviews-evaluation-concept-computer-halogram-scanning-data-business-all-technology-online-reviews-evaluation-112010054.jpg",
      content:"Business woman drawing global structure networking and data exchanges customer connection on dark background",
      category:"Technology",
      date:"on September 20, 2015.",
      width: 2696,
      height: 3546,
    },
    {
      id:"2",
      title:'Sustainable development, eco friendly lifestyle concept. 3d rend',
      url:"https://www.thehansindia.com/assets/earth(14).jpg",
      content:"Sustainable development, eco friendly lifestyle concept. 3d rendering of arrow circle icon on fresh spring meadow with blue sky in background.",
      category:"Technology",
      date:"on october 15,2016",
      width: 500,
      height: 351,
    },
    {
      id: "3",
      title:"Laboratory Test Tube in Science Research Lab",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0A3z1DQrR5MFeZrx7J4WFSnbD9up_6YvuSQ&usqp=CAU",
      content:"Scientist hand holding a laboratory glass test tube filled with yellow liquid for an experiment in a science research lab",
      category:"Technology",
      date:"on March 2, 2019.",
      width: 1280,
      height: 956,
    },
    {
      id: "4",
      title:"Laboratory",
       url:" https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3vbXuHEroioZ5kZ5c_fJBIb5j9JtXC5a49Q&usqp=CAU",
      content:"Scientists working at the laboratory",
      category:"Technology",
      date:"on December 21,2021",
      width: 500,
      height: 500,
    },
    {
      id: "5",
      title:"Flat icons technology, social media, network, computer concept. Abstract background with objects group of elements. star smiley",
      content:"Flat icons technology, social media, network, computer concept. Abstract background with objects with group of elements. star smiley face sale. Share, Like, Comment, Vector illustration Twitter, YouTube, WhatsApp, Snapchat, Facebook, instagram",
      category:"Technology",
      date:"on January 31, 2010",
    url:"https://thumbs.dreamstime.com/z/flat-icons-technology-social-media-network-computer-concept-abstract-background-objects-group-elements-star-smiley-114760907.jpg",
      width: 640,
      height: 428,
    },
  ];
